name: beauty_skin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.7.7

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  path_provider: ^2.0.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  flutter_iconly: ^1.0.2
  badges: ^3.1.1
  equatable: ^2.0.5
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  optimized_cached_image: ^3.0.1
  pull_to_refresh: ^2.0.0
  easy_search_bar: ^2.5.0
  persistent_bottom_nav_bar: ^4.0.2
  uuid: ^3.0.7
  share_plus: ^7.0.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/appLogo/
    - assets/locale/
    - google_fonts/
